#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker222"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "14f9adec79f04e7f9fde134d3d503721" }
]

[assets]
directory = "./public"
